url: "https://desarrolladores-inmobiliario.github.io" # the base hostname & protocol for your site
title: desarrolladores inmobiliario
description: Fraude, Marco Antonio Perez Alejo, Construyetucasa, Construyetudepa, University Depas, Puebla

plugins:
  - jekyll-seo-tag
  